theme: jekyll-theme-minimal
masthead-image: https://user-images.githubusercontent.com/108959229/178078708-8ae033c6-b60d-4be7-9f20-def704bcaf89.jpg
title: Nyan City Studios
description: Un estudio de desarrollo de juegos
